# Generated by Django 3.0 on 2021-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='cruser',
            name='type',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('PRIVILEGED_MEMBER', 'PRIVILEGED_MEMBER'), ('MODERATOR', 'MODERATOR')], default='MEMBER', max_length=50),
        ),
    ]
