# Generated by Django 3.0 on 2021-09-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
